/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Toolkit;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.plaf.basic.BasicMenuBarUI;

/**
 *
 * @author Beck
 */
public class PainelView extends javax.swing.JFrame {

    /**
     * Creates new form ViewPainel
     */
    public PainelView() {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagens/logo_64x.png")));
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    public void getViewInternalFrame(javax.swing.JInternalFrame internalFrame) {
        jDesktopPanePainel.add(internalFrame);
        internalFrame.setVisible(true);
        internalFrame.setLocation((this.jDesktopPanePainel.getWidth() - internalFrame.getWidth()) / 2, (this.jDesktopPanePainel.getHeight() - internalFrame.getHeight()) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonUsuarioAlterar = new javax.swing.JButton();
        jButtonLucroAlterar = new javax.swing.JButton();
        jButtonDespesaAlterar = new javax.swing.JButton();
        jButtonInvestimentoAlterar = new javax.swing.JButton();
        jDesktopPanePainel = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArquivo = new javax.swing.JMenu();
        jMenuItemAdicionarLucro = new javax.swing.JMenuItem();
        jMenuItemAdicionarDespesa = new javax.swing.JMenuItem();
        jMenuItemAdicionarInvestimento = new javax.swing.JMenuItem();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuControle = new javax.swing.JMenu();
        jMenuLucro = new javax.swing.JMenu();
        jMenuItemLucroAdicionar = new javax.swing.JMenuItem();
        jMenuItemLucroAlterar = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuDespesa = new javax.swing.JMenu();
        jMenuItemDespesaAdicionar = new javax.swing.JMenuItem();
        jMenuItemDespesaAlterar = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuInvestimento = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItemInvestimentoAlterar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuUsuario = new javax.swing.JMenu();
        jMenuItemUsuarioAdicionar = new javax.swing.JMenuItem();
        jMenuItemUsuarioAlterar = new javax.swing.JMenuItem();
        jMenuAjuda = new javax.swing.JMenu();
        jMenuItemAjuda = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle Financeiro - v1.0");
        setMinimumSize(new java.awt.Dimension(800, 500));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 102, 102));
        jPanel1.setToolTipText("");
        jPanel1.setMaximumSize(new java.awt.Dimension(5000, 100));

        jButtonUsuarioAlterar.setBackground(new java.awt.Color(0, 102, 102));
        jButtonUsuarioAlterar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonUsuarioAlterar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUsuarioAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user_gray.png"))); // NOI18N
        jButtonUsuarioAlterar.setText("Usuário");
        jButtonUsuarioAlterar.setBorder(null);
        jButtonUsuarioAlterar.setBorderPainted(false);
        jButtonUsuarioAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonUsuarioAlterar.setFocusable(false);
        jButtonUsuarioAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsuarioAlterarActionPerformed(evt);
            }
        });

        jButtonLucroAlterar.setBackground(new java.awt.Color(0, 102, 102));
        jButtonLucroAlterar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonLucroAlterar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLucroAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/report_magnify.png"))); // NOI18N
        jButtonLucroAlterar.setText("Lucro");
        jButtonLucroAlterar.setBorder(null);
        jButtonLucroAlterar.setBorderPainted(false);
        jButtonLucroAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLucroAlterar.setFocusable(false);
        jButtonLucroAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLucroAlterarActionPerformed(evt);
            }
        });

        jButtonDespesaAlterar.setBackground(new java.awt.Color(0, 102, 102));
        jButtonDespesaAlterar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonDespesaAlterar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDespesaAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/report_magnify.png"))); // NOI18N
        jButtonDespesaAlterar.setText("Despesa");
        jButtonDespesaAlterar.setBorder(null);
        jButtonDespesaAlterar.setBorderPainted(false);
        jButtonDespesaAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDespesaAlterar.setFocusable(false);
        jButtonDespesaAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDespesaAlterarActionPerformed(evt);
            }
        });

        jButtonInvestimentoAlterar.setBackground(new java.awt.Color(0, 102, 102));
        jButtonInvestimentoAlterar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButtonInvestimentoAlterar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonInvestimentoAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/report_magnify.png"))); // NOI18N
        jButtonInvestimentoAlterar.setText("Investimento");
        jButtonInvestimentoAlterar.setBorder(null);
        jButtonInvestimentoAlterar.setBorderPainted(false);
        jButtonInvestimentoAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonInvestimentoAlterar.setFocusable(false);
        jButtonInvestimentoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInvestimentoAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonUsuarioAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLucroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDespesaAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonInvestimentoAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(593, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLucroAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDespesaAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInvestimentoAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUsuarioAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonDespesaAlterar, jButtonInvestimentoAlterar, jButtonLucroAlterar, jButtonUsuarioAlterar});

        jDesktopPanePainel.setPreferredSize(new java.awt.Dimension(900, 500));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/background.jpg"))); // NOI18N
        jLabel1.setAutoscrolls(true);

        jDesktopPanePainel.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPanePainelLayout = new javax.swing.GroupLayout(jDesktopPanePainel);
        jDesktopPanePainel.setLayout(jDesktopPanePainelLayout);
        jDesktopPanePainelLayout.setHorizontalGroup(
            jDesktopPanePainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPanePainelLayout.setVerticalGroup(
            jDesktopPanePainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuBar1.setToolTipText("");
        jMenuBar1.setAlignmentY(0.5F);
        jMenuBar1.setOpaque(true);
        jMenuBar1.setUI(new BasicMenuBarUI() {
            public void paint(Graphics g, JComponent c) {
                g.setColor(Color.WHITE);
                g.fillRect(0, 0, c.getWidth(), c.getHeight());
            }
        });
        jMenuBar1.setBorderPainted(false);
        jMenuBar1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuBar1.setInheritsPopupMenu(true);
        jMenuBar1.setPreferredSize(new java.awt.Dimension(160, 30));

        jMenuArquivo.setBackground(new java.awt.Color(255, 255, 255));
        jMenuArquivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/house.png"))); // NOI18N
        jMenuArquivo.setText("Arquivo");

        jMenuItemAdicionarLucro.setBackground(Color.RED);
        jMenuItemAdicionarLucro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItemAdicionarLucro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItemAdicionarLucro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/report_add.png"))); // NOI18N
        jMenuItemAdicionarLucro.setText("Adicionar Lucro");
        jMenuItemAdicionarLucro.setIconTextGap(5);
        jMenuItemAdicionarLucro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAdicionarLucroActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuItemAdicionarLucro);

        jMenuItemAdicionarDespesa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jMenuItemAdicionarDespesa.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItemAdicionarDespesa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItemAdicionarDespesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/report_add.png"))); // NOI18N
        jMenuItemAdicionarDespesa.setText("Adicionar Despesa");
        jMenuItemAdicionarDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAdicionarDespesaActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuItemAdicionarDespesa);

        jMenuItemAdicionarInvestimento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jMenuItemAdicionarInvestimento.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItemAdicionarInvestimento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItemAdicionarInvestimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/report_add.png"))); // NOI18N
        jMenuItemAdicionarInvestimento.setText("Adicionar Investimento");
        jMenuItemAdicionarInvestimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAdicionarInvestimentoActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuItemAdicionarInvestimento);

        jMenuItemSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemSair.setBackground(new java.awt.Color(255, 255, 255));
        jMenuItemSair.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItemSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/door_out.png"))); // NOI18N
        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuItemSair);

        jMenuBar1.add(jMenuArquivo);

        jMenuControle.setBackground(new java.awt.Color(255, 255, 255));
        jMenuControle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/application_cascade.png"))); // NOI18N
        jMenuControle.setText("Controle");

        jMenuLucro.setBackground(new java.awt.Color(255, 255, 255));
        jMenuLucro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/report.png"))); // NOI18N
        jMenuLucro.setText("Lucro");

        jMenuItemLucroAdicionar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItemLucroAdicionar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItemLucroAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/report_add.png"))); // NOI18N
        jMenuItemLucroAdicionar.setText("Adicionar");
        jMenuItemLucroAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLucroAdicionarActionPerformed(evt);
            }
        });
        jMenuLucro.add(jMenuItemLucroAdicionar);

        jMenuItemLucroAlterar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItemLucroAlterar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItemLucroAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/report_magnify.png"))); // NOI18N
        jMenuItemLucroAlterar.setText("Alterar/Remover");
        jMenuItemLucroAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLucroAlterarActionPerformed(evt);
            }
        });
        jMenuLucro.add(jMenuItemLucroAlterar);

        jMenuControle.add(jMenuLucro);
        jMenuControle.add(jSeparator3);

        jMenuDespesa.setBackground(new java.awt.Color(255, 255, 255));
        jMenuDespesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/report.png"))); // NOI18N
        jMenuDespesa.setText("Despesa");

        jMenuItemDespesaAdicionar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jMenuItemDespesaAdicionar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItemDespesaAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/report_add.png"))); // NOI18N
        jMenuItemDespesaAdicionar.setText("Adicionar");
        jMenuItemDespesaAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDespesaAdicionarActionPerformed(evt);
            }
        });
        jMenuDespesa.add(jMenuItemDespesaAdicionar);

        jMenuItemDespesaAlterar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItemDespesaAlterar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItemDespesaAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/report_magnify.png"))); // NOI18N
        jMenuItemDespesaAlterar.setText("Alterar/Remover");
        jMenuItemDespesaAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDespesaAlterarActionPerformed(evt);
            }
        });
        jMenuDespesa.add(jMenuItemDespesaAlterar);

        jMenuControle.add(jMenuDespesa);
        jMenuControle.add(jSeparator2);

        jMenuInvestimento.setBackground(new java.awt.Color(255, 255, 255));
        jMenuInvestimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/report.png"))); // NOI18N
        jMenuInvestimento.setText("Investimento");

        jMenuItem17.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jMenuItem17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItem17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/report_add.png"))); // NOI18N
        jMenuItem17.setText("Adicionar");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenuInvestimento.add(jMenuItem17);

        jMenuItemInvestimentoAlterar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItemInvestimentoAlterar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItemInvestimentoAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/report_magnify.png"))); // NOI18N
        jMenuItemInvestimentoAlterar.setText("Alterar/Remover");
        jMenuItemInvestimentoAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInvestimentoAlterarActionPerformed(evt);
            }
        });
        jMenuInvestimento.add(jMenuItemInvestimentoAlterar);

        jMenuControle.add(jMenuInvestimento);
        jMenuControle.add(jSeparator1);

        jMenuUsuario.setBackground(new java.awt.Color(255, 255, 255));
        jMenuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user.png"))); // NOI18N
        jMenuUsuario.setText("Usuário");

        jMenuItemUsuarioAdicionar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jMenuItemUsuarioAdicionar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItemUsuarioAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user_add.png"))); // NOI18N
        jMenuItemUsuarioAdicionar.setText("Adicionar");
        jMenuItemUsuarioAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuarioAdicionarActionPerformed(evt);
            }
        });
        jMenuUsuario.add(jMenuItemUsuarioAdicionar);

        jMenuItemUsuarioAlterar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItemUsuarioAlterar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItemUsuarioAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user_edit.png"))); // NOI18N
        jMenuItemUsuarioAlterar.setText("Alterar/Remover");
        jMenuItemUsuarioAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuarioAlterarActionPerformed(evt);
            }
        });
        jMenuUsuario.add(jMenuItemUsuarioAlterar);

        jMenuControle.add(jMenuUsuario);

        jMenuBar1.add(jMenuControle);

        jMenuAjuda.setBackground(new java.awt.Color(255, 255, 255));
        jMenuAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/information.png"))); // NOI18N
        jMenuAjuda.setText("Ajuda");

        jMenuItemAjuda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItemAjuda.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItemAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/help.png"))); // NOI18N
        jMenuItemAjuda.setText("Ajuda");
        jMenuItemAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAjudaActionPerformed(evt);
            }
        });
        jMenuAjuda.add(jMenuItemAjuda);
        jMenuAjuda.add(jSeparator4);

        jMenuItemSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        jMenuItemSobre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jMenuItemSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/information.png"))); // NOI18N
        jMenuItemSobre.setText("Sobre");
        jMenuItemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSobreActionPerformed(evt);
            }
        });
        jMenuAjuda.add(jMenuItemSobre);

        jMenuBar1.add(jMenuAjuda);

        setJMenuBar(jMenuBar1);
        jMenuBar1.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jDesktopPanePainel, javax.swing.GroupLayout.DEFAULT_SIZE, 1061, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jDesktopPanePainel, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAdicionarLucroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAdicionarLucroActionPerformed
        getViewInternalFrame(new LucroView());
    }//GEN-LAST:event_jMenuItemAdicionarLucroActionPerformed

    private void jMenuItemAdicionarDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAdicionarDespesaActionPerformed
        getViewInternalFrame(new DespesaView());
    }//GEN-LAST:event_jMenuItemAdicionarDespesaActionPerformed

    private void jMenuItemAdicionarInvestimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAdicionarInvestimentoActionPerformed
        getViewInternalFrame(new DespesaView());
    }//GEN-LAST:event_jMenuItemAdicionarInvestimentoActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemUsuarioAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuarioAdicionarActionPerformed
        getViewInternalFrame(new UsuarioView());
    }//GEN-LAST:event_jMenuItemUsuarioAdicionarActionPerformed

    private void jMenuItemUsuarioAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuarioAlterarActionPerformed
        getViewInternalFrame(new ListUsuariosView(this.jDesktopPanePainel));
    }//GEN-LAST:event_jMenuItemUsuarioAlterarActionPerformed

    private void jMenuItemLucroAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLucroAdicionarActionPerformed
        getViewInternalFrame(new LucroView());
    }//GEN-LAST:event_jMenuItemLucroAdicionarActionPerformed

    private void jMenuItemLucroAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLucroAlterarActionPerformed
        getViewInternalFrame(new ListUsuariosView(this.jDesktopPanePainel));
    }//GEN-LAST:event_jMenuItemLucroAlterarActionPerformed

    private void jMenuItemDespesaAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDespesaAdicionarActionPerformed
        getViewInternalFrame(new DespesaView());
    }//GEN-LAST:event_jMenuItemDespesaAdicionarActionPerformed

    private void jMenuItemDespesaAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDespesaAlterarActionPerformed
        getViewInternalFrame(new ListUsuariosView(this.jDesktopPanePainel));
    }//GEN-LAST:event_jMenuItemDespesaAlterarActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        getViewInternalFrame(new InvestimentoView());
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItemInvestimentoAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInvestimentoAlterarActionPerformed
        getViewInternalFrame(new ListUsuariosView(this.jDesktopPanePainel));
    }//GEN-LAST:event_jMenuItemInvestimentoAlterarActionPerformed

    private void jButtonUsuarioAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsuarioAlterarActionPerformed
        getViewInternalFrame(new ListUsuariosView(this.jDesktopPanePainel));
    }//GEN-LAST:event_jButtonUsuarioAlterarActionPerformed

    private void jButtonLucroAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLucroAlterarActionPerformed
        getViewInternalFrame(new ListUsuariosView(this.jDesktopPanePainel));
    }//GEN-LAST:event_jButtonLucroAlterarActionPerformed

    private void jButtonDespesaAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDespesaAlterarActionPerformed
        getViewInternalFrame(new ListUsuariosView(this.jDesktopPanePainel));
    }//GEN-LAST:event_jButtonDespesaAlterarActionPerformed

    private void jButtonInvestimentoAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInvestimentoAlterarActionPerformed
        getViewInternalFrame(new ListUsuariosView(this.jDesktopPanePainel));
    }//GEN-LAST:event_jButtonInvestimentoAlterarActionPerformed

    private void jMenuItemAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAjudaActionPerformed
        AjudaView ajuda = new AjudaView(this, true);
        ajuda.setVisible(true);
    }//GEN-LAST:event_jMenuItemAjudaActionPerformed

    private void jMenuItemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSobreActionPerformed
        SobreView sobre = new SobreView(this, true);
        sobre.setVisible(true);
    }//GEN-LAST:event_jMenuItemSobreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PainelView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PainelView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PainelView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PainelView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            PainelView painel = new PainelView();
            painel.setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDespesaAlterar;
    private javax.swing.JButton jButtonInvestimentoAlterar;
    private javax.swing.JButton jButtonLucroAlterar;
    private javax.swing.JButton jButtonUsuarioAlterar;
    private javax.swing.JDesktopPane jDesktopPanePainel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenuAjuda;
    private javax.swing.JMenu jMenuArquivo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuControle;
    private javax.swing.JMenu jMenuDespesa;
    private javax.swing.JMenu jMenuInvestimento;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItemAdicionarDespesa;
    private javax.swing.JMenuItem jMenuItemAdicionarInvestimento;
    private javax.swing.JMenuItem jMenuItemAdicionarLucro;
    private javax.swing.JMenuItem jMenuItemAjuda;
    private javax.swing.JMenuItem jMenuItemDespesaAdicionar;
    private javax.swing.JMenuItem jMenuItemDespesaAlterar;
    private javax.swing.JMenuItem jMenuItemInvestimentoAlterar;
    private javax.swing.JMenuItem jMenuItemLucroAdicionar;
    private javax.swing.JMenuItem jMenuItemLucroAlterar;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemSobre;
    private javax.swing.JMenuItem jMenuItemUsuarioAdicionar;
    private javax.swing.JMenuItem jMenuItemUsuarioAlterar;
    private javax.swing.JMenu jMenuLucro;
    private javax.swing.JMenu jMenuUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
